---
name: avalanche

instance_groups:
- name: avalanche
  azs: [z1, z2, z3]
  instances: 1
  vm_type: large
  stemcell: default
  networks: [{name: dynamic}]
  jobs:
  - name: avalanche
    release: avalanche
    properties:
      avalanche:
        metric_count: 500
        label_count: 10
        series_count: 10
        metricname_length: 5
        labelname_length: 5
        value_interval: 30
        series_interval: 60
        metric_interval: 120
        port: 9001

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: avalanche
  version: create  # TODO: update after first final release
  url: .           # TODO: update after first final release
  # sha1:            TODO: update after first final release
